services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./:/minecraft/

  fluent-bit:
    build: ./fluent-bit
    image: fluent-bit
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
      - ./logs:/var/log/app
    environment:
      - FLUENT_BIT_CONFIG=/fluent-bit/etc/fluent-bit.conf
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - ENTITY_NAME=${ENTITY_NAME}
      - HOSTNAME=${HOSTNAME}
      - TZ=Asia/Tokyo
    restart: always
